# Temel image
FROM openjdk:17-jdk-slim

# Çalışma dizini
WORKDIR /app

# Maven wrapper ve pom.xml ekle
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Bağımlılıkları indir
RUN ./mvnw dependency:resolve

# Tüm proje dosyalarını ekle
COPY . .

# Uygulamayı build et
RUN ./mvnw clean package -DskipTests

# Çalıştırılacak jar dosyasını belirle
CMD ["java", "-jar", "target/registration-0.0.1-SNAPSHOT.jar"]
